name: cfc_rl_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.5
  - gym
  - matplotlib
  - tensorflow=2.7.0
  - pip
  - pip:
    - gymnasium
    - ncps
    - ray==2.10.0